puts "In the first case x will print 3 because x is initialized
outside the method invocation. In the second case an error message will 
be received because the x variable is initialized from inside the method
invocation and is not available in outside scope."